"""
Django settings for dicom_project project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0sm57#a5dfeti93l=cz15kp*+)hsa2^%(6d%f^yn@0jh_(0x(f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'dicom_app',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # This should be at the top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]

ROOT_URLCONF = "dicom_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dicom_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Allow all origins for development purposes (use cautiously in production)
CORS_ALLOW_ALL_ORIGINS = True

# or we can specify specific urls
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',  # Your React development server
#     'http://127.0.0.1:3000',
# ]


# dicom_project/settings.py

import os

MODELS_DIR = os.path.join(BASE_DIR, 'dicom_app/models')  # Path to your model folder



# os.environ["nnUNet_raw"] = os.path.abspath("dicom_app/nnunet_engine/nnUNet_raw")
# os.environ["nnUNet_preprocessed"] = os.path.abspath("dicom_app/nnunet_engine/nnUNet_preprocessed")
# os.environ["nnUNet_results"] = os.path.abspath("dicom_app/nnunet_engine/nnUNet_results")

# In your Django settings.py or as system environment variables
import os
os.environ['nnUNet_raw'] = r"C:\Graduation Project\Code\Dicom viewer backend pycharam\Trial 1\dicom_project\dicom_app\nnunet_engine\nnUNet_raw"
os.environ['nnUNet_preprocessed'] = r"C:\Graduation Project\Code\Dicom viewer backend pycharam\Trial 1\dicom_project\dicom_app\nnunet_engine\nnUNet_preprocessed"
os.environ['nnUNet_results'] = r"C:\Graduation Project\Code\Dicom viewer backend pycharam\Trial 1\dicom_project\dicom_app\nnunet_engine\nnUNet_results"

import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''
os.environ['nnUNet_USE_CUDA'] = '0'

import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:128'
